CREATE DATABASE IF NOT EXISTS glean;

USE glean;

DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS hosts;

CREATE TABLE books (
    title VARCHAR(200) PRIMARY KEY,
    content VARCHAR(100000)
);

CREATE TABLE hosts (
    hostName VARCHAR(30),
    location VARCHAR(100) PRIMARY KEY
);
